[package]
name = "rumd"
version = "0.1.0"
authors = ["Carlos L. Torres <cltorrespr@gmail.com>"]
edition = "2018"

[dependencies]
tokio = {version = "0.2", features = ["macros"] }
warp = "0.2"
log = "0.4"
pretty_env_logger = "0.4"
